language: java
jdk:
  -openjdk8


branches:
  only:
    - master

# Travis CI Server's Home
cache:
  directories:
    - '$HOME/.m2.repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Email alert when CI successfully executed
notifications:
  email:
    recipients:
      - rlarkdals579@naver.com