language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server's Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Value from Travis repo settings
    secret_access_key: $AWS_SECRET_KEY # Value from Travis repo settings
    bucket: kangmin-springboot-build # S3 bucket
    region: us-east-2
    skip_cleanup: true
    acl: private # set access to zip file as a private
    local_dir: deploy # directory <- before_deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY  # Value from Travis repo settings
    secret_access_key: $AWS_SECRET_KEY  # Value from Travis repo settings
    bucket: kangmin-springboot-build # S3 Bucket
    key: springboot-webservice.zip
    bundle_type: zip
    application: kangmin-springboot2-webservice # CodeDeploy Application name
    deployment_group: kangmin-springboot2-webservice-group # CodeDeploy Deploy Group
    region: us-east-2
    wait-until-deployed: true

# Email alert when CI successfully executed
notifications:
  email:
    recipients:
      - rlarkdals579@naver.com