version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh #terminate springboot which does not connected with nginx
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh #Start new version of Springboot which is not connected with nginx
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # checking springboot successfully executed.
      timeout: 60
      runas: ec2-user